# ALMACEN CENTRAL
SELECT CODIGO,PRODUCTO,IFNULL(TOTAL_INVENTARIO,0) AS INVENTARIO,IFNULL(TOTAL_ENTRADAS,0) AS ENTRADAS,
		 IFNULL(TOTAL_ENTRADAS_TRANSF,0) AS ENTRADAS_TRANSF,
		 IFNULL(TOTAL_DESCARGAS,0) AS DESCARGAS,
		 IFNULL(TOTAL_TRANSFERENCIAS,0) AS TRANSFERENCIAS,IFNULL(STOCK_ALMACEN,0) AS STOCK_ALMACEN,
		 IFNULL(SALDO_REAL,0) AS SALDO_REAL,IFNULL(STOCK_ALMACEN,0)-IFNULL(SALDO_REAL,0) AS DIFERENCIA
FROM v_check_saldos_almCentral_Inv
WHERE IFNULL(STOCK_ALMACEN,0)-IFNULL(SALDO_REAL,0)<>0
ORDER BY DIFERENCIA;
# OTROS ALMACENES MENOS 19 - DETERIORADOS, 38 - VENCIDOS, 42 - ALMACEN EXTERNO
SELECT * FROM v_check_saldos_allSubw_Inv WHERE DIFERENCIA<>0 AND ALMACEN NOT IN (19,38,42) ORDER BY ALMACEN;
# ALMACEN EMERGENCIAS
SELECT CODIGO,PRODUCTO,IFNULL(TOTAL_ENTRADAS,0) AS ENTRADAS,
		 IFNULL(TOTAL_ENTRADAS_TRANSFERENCIA,0) AS ENTRADAS_TRANSF,
		 IFNULL(TOTAL_VENTAS,0) AS VENTAS,
		 IFNULL(TOTAL_TRANSFERENCIAS,0) AS TRANSFERENCIAS,IFNULL(STOCK_ALMACEN,0) AS STOCK_ALMACEN,
		 IFNULL(SALDO_REAL,0) AS SALDO_REAL,IFNULL(STOCK_ALMACEN,0)-IFNULL(SALDO_REAL,0) AS DIFERENCIA
FROM v_check_saldos_almEmergencia
WHERE IFNULL(STOCK_ALMACEN,0)-IFNULL(SALDO_REAL,0)<>0
ORDER BY DIFERENCIA;
#PENDIENTES
SELECT * FROM entry WHERE `status` NOT IN ('finalizado','eliminado') AND CAST(created AS DATE)>='2023-01-01';
SELECT * FROM discharge WHERE `status` NOT IN ('finalizado','eliminado') AND CAST(created AS DATE)>='2023-01-01';
SELECT * FROM sales WHERE `status` NOT IN ('finalizado','eliminado') AND CAST(`create` AS DATE)>='2023-01-01';


